version: "3.5"

services:
  redis:
    image: redis:6
    container_name: ${PROJECT_NAME}_redis
    restart: unless-stopped
    # Set maxmemory and policy, feel free to adjust
    command: "redis-server --maxmemory 1024mb --maxmemory-policy allkeys-lru"
    expose:
      - 6379
    networks:
      - service

  mysql:
    image: mysql:8 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - 3306:3306
    networks:
      - database
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--sql-mode=NO_ENGINE_SUBSTITUTION'
      ]
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/database:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_USERPASS
      MYSQL_ROOT_PASSWORD: $DB_ROOTPASS
    profiles: [ "dev" ]
    restart: unless-stopped

  php-fpm:
    container_name: ${PROJECT_NAME}_php
    build: ./php
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    expose:
      - 20002
      - 20003
      - 20199
    tmpfs: /var/temp #上传临时文件夹
    working_dir: /var/www
    tty: true
    volumes:
      - ../crmebpro:/var/www #程序运行目录
      - ../crmebpro/runtime:/var/www/temp #程序缓存目录
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/supervisor:/etc/supervisor
      - ./logs/php:/var/log/php/
      - ./logs/supervisor:/var/log/supervisor/
    networks:
      - application
      - service
      - database

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx
    restart: unless-stopped
    ports:
      - ${CRMEB_PORT}:80
    depends_on:
      - php-fpm
    environment:
      TZ: Asia/Shanghai
    working_dir: /var/www
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ../crmebpro:/var/www #程序运行目录
      - ../crmebpro/runtime:/var/www/temp #程序缓存目录
    networks:
      - application

  pma:
    container_name: ${PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - ${PMA_PORT}:80
    networks:
      - database
    environment:
      PMA_HOST: $DB_HOST
      PMA_PORT: $DB_PORT
      PMA_USER: root
      PMA_PASSWORD: $DB_USERPASS
      UPLOAD_LIMIT: 1024M
    profiles: [ "dev" ]

networks:
  application:
    driver: bridge
  service:
    driver: bridge
  database:
    driver: bridge
